### ISSUE TITLE
Is planned to release a new version?

### ISSUE THREAD

**Issue by markitosgv** [villfa/php-invert-color#17]
Last tagged version was 0.5, is it possible to add a new release in composer?

thanks!

**Comment by villfa** [comment]
Hi,
There was no new release since 0.5 because all changes since then are about the CI.
Is there a change you need that it'll justify a new release?

**Comment by villfa** [comment]
Closing since 0.5.1 has just been released: https://github.com/villfa/php-invert-color/releases/tag/0.5.1
