### ISSUE TITLE
Failure to Acknowledge const STR_PAD_LEFT

### ISSUE THREAD

**Issue by kiusau** [villfa/php-invert-color#5]
Hi, I really like this piece of software, but sometime in the past several months it stopped working.  I am running in PHP 7.2 and my system is rejecting the constant STR_PAD_LEFT in https://github.com/villfa/php-invert-color/blob/master/src/Color.php.

The error message reads:  [05-Jan-2020 23:08:20 UTC] PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/thege0/vendor/villfa/invert-color/src/Color.php on line 16.

I am an advanced novice in webpage development and am just learning how to use GIT, so please excuse me for not being able to be anymore helpful.

Roddy at nudge.online

**Comment by villfa** [comment]
Hi,
This error message appears only with PHP-7.0 or less, see: https://3v4l.org/bShot
So the problem comes from your system.

**Comment by kiusau** [comment]
Thank you. I have upgraded to 7.2, and it is now working fine. Please go to https://www.grammarcaptive.com/overview.html and click on any of the items in the Local Search submenu in the navigation bar to see how I have employed your software.

In appreciation for your creation I have written a credit for you and your software in the page's Credits section that is also available in the same navigation bar.

Have a great 2020!

Roddy A. Stegemann, A.B., M.A., M.A.
Founder/Owner of nudge.online
www.nudge.online

kiusau@me.com
admin@nudge.online

Twitter: @kiusau

Mobile: +1 (206) 291-8468

909 Boren Avenue
The Cabrini, Suite 603
First Hill, Seattle
Washington, USA 98104

2020/01/06 1:17、Fabien Villepinte <notifications@github.com> のメッセージ:
